name: Dispatcher
on:
  pull_request:
    types: [opened]

jobs:
  dispatch:
    name: Dispatch
    runs-on: ubuntu-latest
    strategy:
      matrix:
        repo: ['FChikh/sync_repos_private']
    timeout-minutes: 5
    steps:
      - name: Dispatch to workflows
        run: |
            curl -H "Accept: application/vnd.github.everest-preview+json" \
            -H "Authorization: token ${{ secrets.PRIVATE_REPO_TOKEN }}" \
            --request POST \
            --data '{"event_type": "new_pull"}' https://api.github.com/repos/${{ matrix.repo }}/dispatches
