name: Sync Public Pull Requests to Private

on:
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  sync_public_to_private:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Public Repo
        uses: actions/checkout@v2
        with:
          repository: FChikh/sync_repo_public
          ref: main
#           token: ${{ secrets.PUBLIC_REPO_TOKEN }}

      - name: Checkout Private Repo
        uses: actions/checkout@v2
        with:
          repository: FChikh/sync_repo_private
          ref: main
#           token: ${{ secrets.PRIVATE_REPO_TOKEN }}

      - name: Sync Public Pull Requests to Private
        run: |
          git config user.email "github-actions@github.com"
          git config user.name "GitHub Actions"
          git fetch --all
          git checkout -b pr-${{ github.event.number }}-public origin/${{ github.head_ref }}
          git push -f origin pr-${{ github.event.number }}-public:pr-${{ github.event.number }}-public

          # Create a pull request in the private repository
          TOKEN=$PRIVATE_REPO_TOKEN
          GITHUB_ACTOR=$PRIVATE_REPO_OWNER
          GITHUB_REPOSITORY=$PRIVATE_REPO_NAME
          PR_HEAD_BRANCH=pr-${{ github.event.number }}-public
          PR_BASE_BRANCH=main
          PR_TITLE=$(echo "${{ github.event.pull_request.title }}" | sed 's/\[public\] //')
          PR_BODY="${{ github.event.pull_request.body }}\n\n[Synced from public repository](${{ github.event.pull_request.html_url }})"
          PR_MAINTAINER_CAN_MODIFY=true
          PR_DRAFT=false
          PR_RESPONSE=$(curl -s -X POST -H "Authorization: token ${TOKEN}" -H "Accept: application/vnd.github.v3+json" https://api.github.com/repos/${GITHUB_REPOSITORY}/pulls -d "{\"title\":\"${PR_TITLE}\",\"body\":\"${PR_BODY}\",\"head\":\"${GITHUB_ACTOR}:${PR_HEAD_BRANCH}\",\"base\":\"${PR_BASE_BRANCH}\",\"maintainer_can_modify\":${PR_MAINTAINER_CAN_MODIFY},\"draft\":${PR_DRAFT}}")
          echo "Pull Request Created: $PR_RESPONSE"
